// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hloiabotffogdnxnitkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsb2lhYm90ZmZvZ2RueG5pdGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjUwMDIsImV4cCI6MjA2ODc0MTAwMn0.9l7otzx1nwJvopl4zc_zpT5MMvi6LhNs9VZzqJeT0ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});